version: "3"
services:

  certbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=certbot
      - PYTHONDONTWRITEBYTECODE=1
      - AWS_PROFILE=<<AWS_LOCAL_PROFILE>>
      - WEBHOOK=<<LAMBDA_GATEWAY_URI>>
      - EMAIL=<<EMAIL>>
    volumes:
      - ./src:/src
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host