version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host